id: medcom.fhir.dk.xdsdocuments
canonical: http://medcomfhir.dk/ig/xdsdocuments
name: MedCom XDS Documents
title: Danish XDS Documents profiles
description: Danish XDS Documents profiles consists of both the Documents themselves being FHIR Documents or Messages and their corresponding DocumentReferences
status: draft # draft | active | retired | unknown
version: 1.0.0-trial-use-2
fhirVersion: 4.0.1 # https://www.hl7.org/fhir/valueset-FHIR-version.html
copyrightYear: 2026+
releaseLabel: trial-use # ci-build | draft | qa-preview | ballot | trial-use | release | update | normative+trial-use
jurisdiction: urn:iso:std:iso:3166#DK "Denmark"
publisher:
  name: MedCom
  url: https://medcom.dk/
  email: fhir@medcom.dk

dependencies:
  hl7.fhir.uv.xver-r5.r4: 0.1.0
  hl7.fhir.dk.core: 3.6.0
  medcom.fhir.dk.core: 4.0.0
  ihe.iti.mhd: 4.2.3
  medcom.fhir.dk.xdsmetadata: 2.0.0-trial-use-1

menu:
  Home: index.html
  Profiles: profiles.html
  Project Specific DocumentReferences: documentreferences.html
  Extensions: extensions.html
  Artifacts: artifacts.html
  Governance and guidance:
    Use Cases: usecases.html
    Governance: governance.html
    Profiling FHIR Document standards: profilingclinicalcontent.html
  More:
    Table of Contents: toc.html
    Downloads: downloads.html
    Dependencies: dependencies.html

parameters:  
  apply-version: false
  default-version: true
  apply-publisher: false
  default-publisher: true
  pin-canonicals: pin-multiples
  excludettl: true
  special-url: [urn:oid:1.2.208.184.100.1]