Alias: $DanishSnomed = http://snomed.info/sct/554471000005108
Alias: $obligation = http://hl7.org/fhir/StructureDefinition/obligation
Alias: $IANALanguageOID = urn:ietf:bcp:47
Alias: $IANAMediaOID = urn:ietf:bcp:13
Alias: $loinc = http://loinc.org
Alias: $MedComXDSTypeCode = http://medcomfhir.dk/ig/xdsmetadata/CodeSystem/MedCom-xds-typecode-CS
Alias: $MedComXDSTypeCodeVS = http://medcomfhir.dk/ig/xdsmetadata/ValueSet/MedCom-xds-typecode-VS
Alias: $MedComXDSClassCode = http://medcomfhir.dk/ig/xdsmetadata/CodeSystem/MedCom-xds-classcode-CS
Alias: $MedComXDSClassCodeVS = http://medcomfhir.dk/ig/xdsmetadata/ValueSet/MedCom-xds-classcode-VS
Alias: $MedComXDSMimeTypeVS = http://medcomfhir.dk/ig/xdsmetadata/ValueSet/MedCom-xds-mimetype-xml-VS // TODO: Should probably be changed to a non 'xml' only url
Alias: $MedComXDSLanguageCodeVS = http://medcomfhir.dk/ig/xdsmetadata/ValueSet/MedCom-xds-languagecode-VS
Alias: $MedComXDSFormatCodeCS = http://medcomfhir.dk/ig/xdsmetadata/CodeSystem/MedCom-xds-formatcode-CS
Alias: $MedComXDSFormatCodeVS = http://medcomfhir.dk/ig/xdsmetadata/ValueSet/MedCom-xds-formatcode-VS
Alias: $MedComXDSHealthcareFacilityTypeCodeVS = http://medcomfhir.dk/ig/xdsmetadata/ValueSet/MedCom-xds-HealthcareFacilityTypeCode-VS
Alias: $MedComXDSPracticeSettingCodeVS = http://medcomfhir.dk/ig/xdsmetadata/ValueSet/MedCom-xds-PracticeSettingCode-VS
Alias: $MedComXDSHomeCommunityId = http://medcomfhir.dk/ig/xdsmetadata/CodeSystem/MedCom-xds-homeCommunityId-CS
Alias: $MedComXDSHomeCommunityIdVS = http://medcomfhir.dk/ig/xdsmetadata/ValueSet/MedCom-xds-homeCommunityId-VS